GET http://localhost:3000/quotes/

###
GET http://localhost:3000/quotes/5e5a5934897dd93fd07be33d

###
POST http://localhost:3000/quotes/
Content-Type: application/json

{ 
  "quote" : "salut salut salut salut salut",
  "author" : "john"
}

###
POST http://localhost:3000/test
Content-Type: application/json

{ 
  "quote" : "yolo",
  "author" : "john"
}

###
DELETE http://localhost:3000/quotes/5eb2ea606649c80f5c6e083f

###
PATCH http://localhost:3000/quotes/5e5a5934897dd93fd07be33d
Content-Type: application/json

{ 
  "quote" : "salut salut salut salut salut",
  "author" : "Hello"
}